### PR TITLE
Update Schemas to V3.0RC02

### PR DESCRIPTION
**Pull request by sebbader**
This PR represents the final step to publish and release all the work 
for the metamodel version 3.0 release candidate RC02. 
Contains the generated schemas for JSON, XML, and RDF/SHACL.
For the first time, the schemas have been generated based on the code 
from https://github.com/aas-core-works/aas-core-codegen. 
This project contains a formal model representation of the AAS part 1 
definitions.

### CODE REVIEW

**Comment by sebbader** [comment]
The JSON Schema file has been the base for the [SwaggerHub Part1 Metamodel Schema](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0RC02#), which has been transformed to [JSON OpenAPI](https://thebrenny.github.io/json-to-oapi/) and OpenAPI YAML definitions.

Todo before merging the PR:
- [ ]  Replace YAML files with latest SwaggerHub Part1 Domain Schema @sebbader

**Comment by sebbader** [comment]
I have reviewed the current JSON, XML, and RDF schema files (cannot be a reviewer as I also created the PR). The changes are - as much as it's possible through a manual review - correct and represent the specifications from Part1 V3.0RC02. 

Additional reviews are welcome!

**Comment by mristin** [comment]
@sebbader also readmes need to be updated. Could you please add it to your todo list above?

**Comment by mristin** [comment]
@sebbader we should also not forget to squash the commits before merging -- another item for your todo list.

**Comment by sebbader** [comment]
Update of the YAML directory has been done with https://github.com/admin-shell-io/aas-specs/commit/988272fbe8155764e17c5d7ca3489b29737c56f8. I stored the old state in https://github.com/admin-shell-io/aas-specs/tree/backup/yaml-1.0RC01_august2022, just in case we need it later.

**Comment by sebbader** [comment]
> Please update the README.md from the PR #209. It removes any mention oft the DRAFT status of RC02.

@g1zzm0 you reference a PR with changes in the CONTRIBUTING file. Please be aware that #185 also changes this file, deleting some of the parts which you have updated. Is the current state of CONTRIBUTING.md in `master` now up-to-date or `draft-V3RC02-schemas`? 
(I want to avoid that we resolve the certainly appearing merge conflict by reintroducing the old text...)

**Comment by g1zzm0** [comment]
> @g1zzm0 you reference a PR with changes in the CONTRIBUTING file. Please be aware that #185 also changes this file, deleting some of the parts which you have updated. Is the current state of CONTRIBUTING.md in `master` now up-to-date or `draft-V3RC02-schemas`? (I want to avoid that we resolve the certainly appearing merge conflict by reintroducing the old text...)

The CONTRIBUTING was not changed in #185, because it was closed. The conflict in #181 and #207 was resolved and can be merged.

**Comment by BirgitBoss** [comment]
JSON file has a breaking change compared to previous versions w.r.t. handling of primitive types. This was not approved yet by working group. See my PR https://github.com/admin-shell-io/aas-specs/pull/236 changing the serilaization rules in the README: The schema itself still needs to be updated. The corresponding PR is not yet available.

**Pull request merged**
