### PR TITLE
Update Approval Process in Contribution Guide

### PR DESCRIPTION
**Pull request by BirgitBoss**
No profiles in contribution guide, only roles.

Minor:
Add name of Joint Working Group.

### CODE REVIEW

**Comment by g1zzm0** [comment]
With this change, it is no longer possible to add a reviewer via `review-requested:`. How does one know who are the responsible designated reviewers?

**Review by aorzelskiGH — APPROVED** [review]

**Comment by g1zzm0** [comment]
@aorzelskiGH Since you have approved this change, how is it possible for you to add a reviewer via `review-requested:`?

**Comment by sebbader** [comment]
@BirgitBoss and @g1zzm0 please resolve the conflicts and merge the PR.

**Comment by mristin** [comment]
Best if we created a separate branch and squashed the commits. @BirgitBoss and @g1zzm0 are you OK if I take over?

**Comment by mristin** [comment]
@sebbader @BirgitBoss @g1zzm0 the readmes have to be updated as well.

**Comment by mristin** [comment]
@BirgitBoss @g1zzm0 please do go ahead, re-review this PR and merge it in as @sebbader suggested.

**Comment by sebbader** [comment]
This PR has been approved already, and the conflicts have been resolved. I merge this PR directly into `master` as the current - incorrect - statements in the contributing guide present a major issue and should not stay until the next release is ready.

**Pull request merged**
