### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by BirgitBoss**
Contributing.md was updated for branch V3.0RC02 
(was already accepted and merged with master, 
therefore no new review needed.

### CODE REVIEW

**Comment by BirgitBoss** [comment]
Second error has nothing to do with this PR since only Contribution.md was changed
 Failed to compile the schema: xml\AAS.xsd
Type 'http://www.w3.org/2001/XMLSchema:dateTimeStamp' is not declared, or is not a simple type.
XML validation failed.

**Comment by sebbader** [comment]
> Second error has nothing to do with this PR since only Contribution.md was changed
> Failed to compile the schema: xml\AAS.xsd
> Type 'http://www.w3.org/2001/XMLSchema:dateTimeStamp' is not declared, or is not a simple type.
> XML validation failed.

That's a really strange one, especially as other PRs pass the test. I have created #226 to reproduce it, and received the same error. However, I was not able to reproduce or debug the script error locally, as I do not have a Win machine available. Can someone else check, too?

**Comment by mristin** [comment]
If not fixed till Wednesday, I'll have a look.

**Comment by mristin** [comment]
@BirgitBoss I suspect the HEAD of your fork is out of sync with the origin.

**Comment by sebbader** [comment]
I used #226 to debug the validation error. Looks like `xs:dateTimeStamp`, `xs:dayTimeDuration`, and `xs:yearMonthDuration` cause the error but e.g. `xs:anyURI`, `xs:base64Binary`, or `xs:boolean` don't affect it. Strange behaviour.

**Comment by sebbader-sap** [comment]
@mristin please take a look at it tomorrow. It seems like these datatypes have not made it into the schema files (=XSD files), even though being part of the standard (=HTML file). If you do not find a better solution, I propose to delete them from https://github.com/admin-shell-io/aas-specs/blob/7ec3e0807bd4a528674a678d1a0d581c45a747ff/schemas/xml/AAS.xsd#L1101 (please note: I also think we should explicitly not delete them from the enum at https://github.com/admin-shell-io/aas-specs/blob/7ec3e0807bd4a528674a678d1a0d581c45a747ff/schemas/xml/AAS.xsd#L968 ).
Of course we then need to write a short sentence in the XML Readme that and why we did this...

**Comment by mristin** [comment]
@sebbader these member types were added in XSD 1.1. If you use a validator which validates using XSD 1.0, it throws an error.

The C# validator we are using is probably based on XSD 1.0. It is only strange that CI did not fail before, when I merged in these changes, and gave a green light.

**Comment by mristin** [comment]
@sebbader I figured out why CI didn't fail. I mistakenly pushed a commit to draft branch (https://github.com/admin-shell-io/aas-specs/commit/7ec3e0807bd4a528674a678d1a0d581c45a747ff#diff-eb36a693a0afb92c36c3cae8975320c12cd7eccaa3cf24b3441ca4131d3cab64) instead of creating a pull request, and CI was set to run only on pull requests.

**Comment by mristin** [comment]
@sebbader I'll update the validator tomorrow.

**Comment by mristin** [comment]
@sebbader great, C# doesn't support XSD 1.1: https://stackoverflow.com/questions/61293382/xsd-1-1-validation-for-both-java-and-net-c

Let's discuss this in email as it needs a broader discussion.

**Comment by mristin** [comment]
@sebbader the issue with CI has been fixed in #230. Please rebase this PR and then you can merge it.

**Pull request closed without merging**
