### PR TITLE
Second Try for #226

### PR DESCRIPTION
**Pull request by sebbader**
Original #226 has failing XML schema checks and slightly differs to the Contributing file in `master`.

### CODE REVIEW

**Comment by g1zzm0** [comment]
Sorry, but this is the outdated version. Please close the PR

**Comment by BirgitBoss** [comment]
No, the  version in this branch is outdated. The version in the master branch is the actual version.  In this version one additional hint w.r.t linking issue was added.

**Comment by BirgitBoss** [comment]
But I do not understand how updating an .md file can cause schema validations...

**Comment by g1zzm0** [comment]
No in the rc02 branch the information about the is review process and maintainer is missing. 
This was changed between RC01 in main and RC02 in rc02 branch.

**Comment by g1zzm0** [comment]
> But I do not understand how updating an .md file can cause schema validations...
Because you're working on an outdated version.
Please close this PR and apply the changes to the RC2.

**Comment by sebbader** [comment]
Let's wait a second. The change of this PR is not outdated, it's rather a duplicate. And I created it to debug the issue with the validation script.

**Comment by sebbader** [comment]
Ok, I could track it down to `xs:dateTimeStamp`, `xs:dayTimeDuration`, and `xs:yearMonthDuration`. Removing them solves the problem. Any ideas why?

**Comment by sebbader** [comment]
I have changed this PR to `draft` to not interfere with #226 .

**Comment by mristin** [comment]
@sebbader This seems like XSD 1.0 vs XSD 1.1 issue.

**Comment by sebbader** [comment]
We have found the reason for the failing validation, will close this PR therefore.

**Pull request closed without merging**
