### PR TITLE
Add Release Section to the README

### PR DESCRIPTION
**Pull request by sebbader**
We have now several releases available. Unfortunetly, they are quite hard to find, especially for users who are not
that much experienced with GitHub. Now, we reader can directly find the releases in the README.

### CODE REVIEW

**Review by sebbader — COMMENTED** [review]
Releases for the overview README:

Adding a Section for the published releases and links to their location.
Decision of the "UAG Verwaltungsschale" from 21.4.2021.

**Comment by Manu3756** [comment]
@sebbader  if you resolve the conflicts I can merge it.

**Comment by sebbader** [comment]
no clue what went wrong, the conflict was actually none...

**Review by Manu3756 — COMMENTED** [review]
-

**Pull request merged**
