### PR TITLE
Editorial Changes

### PR DESCRIPTION
**Pull request by BirgitBoss**
- remove prefix IDTA-01001 and IDTA-01xxx from files
- update all xref:
- merge files from Annex and SharedAnnex to Annex folder

### CODE REVIEW

**Review by zrgt — CHANGES_REQUESTED** [review]
Please see #441

**Comment by BirgitBoss** [comment]
substituted by #441

**Comment by BirgitBoss** [comment]
@zrgt may you please look for the confict , I just merged your PR #441. Thank you

**Review by zrgt — APPROVED** [review]

**Comment by zrgt** [comment]
@BirgitBoss the PR is ready to be merged now

**Pull request merged**
