### PR TITLE
Fix outdated external links

### PR DESCRIPTION
**Pull request by mhrimaz**
The links to the meta-model documents, SwaggerHub, *etc.* are outdated.
We fix the links as well as a couple of small typos.

### CODE REVIEW

**Comment by mristin** [comment]
LGTM! @sebbader-sap please review as well?

**Review by sebbader-sap — APPROVED** [review]
Great work, thanks a lot!

**Comment by mristin** [comment]
@mhrimaz I have to update the CI since GitHub deprecated netcore 3.1 on their default images. I'll try to do this tomorrow, and then you can re-base your pull request.

**Comment by mristin** [comment]
@mhrimaz I have fixed the CI in https://github.com/admin-shell-io/aas-specs/pull/286, and now it works in the latest revision of the master branch. Could you please rebase your fork so that we can re-run it on your changes?

**Comment by mristin** [comment]
@mhrimaz thanks again!

**Pull request merged**
